// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vorrxdvfveflnnvchlcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvcnJ4ZHZmdmVmbG5udmNobGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjY5OTIsImV4cCI6MjA2NzcwMjk5Mn0.hfVioxBaVWjOiMevAI9YDWO6U2pFf-GNKRb-ZJ_jyOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});